# Generated by Django 3.2.8 on 2024-11-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20241128_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacion',
            name='portada',
            field=models.ImageField(null=True, upload_to='libros/', verbose_name='Imagen'),
        ),
    ]
